name = "elementary"
license = "MIT"
licenselink = "https://github.com/fathyar/elementary/blob/master/LICENSE.md"
description = "Minimal Hugo theme without any tracking or external dependencies."
homepage = "https://github.com/fathyar/elementary"
tags = ["blog", "minimal", "dark mode", "simple", "clean", "light", "responsive", "fast", "no-tracking", "privacy"]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "fathyar"
  homepage = "https://github.com/fathyar"

[original]
  author = "morph"
  homepage = "morph.sh"
  repo = "https://github.com/colorchestra/smol"
